### ISSUE TITLE
容器安装后， 启动不了

### ISSUE THREAD

**Issue by gitupdate** [zhao-zg/jd-login#7]
这是 docker ps 截图
![image](https://github.com/user-attachments/assets/4099c5d6-e623-4717-936b-7c068d918da0)

这是日志截图
![image](https://github.com/user-attachments/assets/070c39be-8958-4f0a-97d6-5c404d548ab7)

**Comment by gitupdate** [comment]
> 忘记改了，现在已修改readme

感谢回复， 不过替换 部署命令后， `docker-compose down` 停止并删除容器； 然后重新部署， 查看日志日期还是有下面截图问题
![image](https://github.com/user-attachments/assets/37b90156-2487-4224-8dd6-f2961b565ad0)

**Comment by zhao-zg** [comment]
这个应该是你自身机器配置问题

**Comment by gitupdate** [comment]
好
